import { projects } from "../data/content";
import ProjectDetail from "../components/ProjectDetail";

const project = projects.find((p) => p.slug === "dadip");

const BASE = import.meta.env.BASE_URL;

export default function DadipPage() {
  return (
    <ProjectDetail project={project}>
      {/* Overview */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-4">Overview</h2>
        <p className="text-slate-300 leading-relaxed mb-4">
          Mapping and monitoring the Greenland Ice Sheet is critically important
          for understanding ice-sheet dynamics, mass balance, and contributions
          to sea-level rise. Modern satellite altimeter missions like NASA's
          ICESat-2 collect measurements at extremely high resolution along
          sub-orbital ground tracks (0.7m spacing), but with kilometer-wide gaps
          between tracks.
        </p>
        <p className="text-slate-300 leading-relaxed mb-4">
          The challenge: how to generate a spatially continuous, gridded
          representation of the ice surface from data that is ultra-dense along
          tracks but sparse between them, while preserving the complex spatial
          variability that standard statistical averages cannot capture.
        </p>
        <p className="text-slate-300 leading-relaxed">
          <span className="text-white font-medium">DADIP</span> (Data
          Aggregation and Directional Interpolation Pipeline) solves this by
          combining efficient data aggregation with advanced geostatistical
          interpolation. The algorithm achieves a{" "}
          <span className="text-emerald-400 font-medium">
            90%+ speed improvement
          </span>{" "}
          over previous approaches while producing high-quality elevation and
          roughness maps of the entire Greenland Ice Sheet.
        </p>
      </section>

      {/* Before / After */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">
          Results: Before & After Interpolation
        </h2>
        <div className="grid md:grid-cols-2 gap-6">
          <div>
            <p className="text-slate-400 text-sm mb-2 font-medium">
              Raw satellite tracks (before)
            </p>
            <img
              src={`${BASE}images/dadip/elevation_before_interpolation.png`}
              alt="Greenland elevation data before interpolation - raw satellite tracks"
              className="rounded-xl border border-slate-700 w-full"
            />
            <p className="text-slate-500 text-xs mt-2">
              Raw ICESat-2 ground tracks showing the sparse, track-aligned
              distribution of elevation measurements.
            </p>
          </div>
          <div>
            <p className="text-slate-400 text-sm mb-2 font-medium">
              Interpolated elevation map (after)
            </p>
            <img
              src={`${BASE}images/dadip/elevation.jpeg`}
              alt="Greenland elevation map after DADIP interpolation"
              className="rounded-xl border border-slate-700 w-full"
            />
            <p className="text-slate-500 text-xs mt-2">
              Continuous elevation map of the Greenland Ice Sheet generated by
              DADIP using Ordinary Kriging interpolation.
            </p>
          </div>
        </div>
      </section>

      {/* Pipeline */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">The DADIP Pipeline</h2>
        <p className="text-slate-300 mb-6">
          The interpolation framework transforms satellite-derived measurements
          into structured spatial maps through four computational stages:
        </p>
        <div className="space-y-4">
          {[
            {
              step: "1",
              title: "Data Preprocessing",
              desc: "Geographic coordinates are converted to UTM projection, spatially cropped to the study region using a polygonal mask, and filtered to remove physically implausible values. Runs in O(n) time.",
              color: "sky",
            },
            {
              step: "2",
              title: "Grid Construction & Median Computation",
              desc: "Measurements are grouped into grid cells at user-defined resolution. Within each cell, the median-of-medians algorithm (worst-case O(n)) is used instead of sorting to compute a representative value, providing robustness to uneven sampling and measurement artifacts.",
              color: "emerald",
            },
            {
              step: "3",
              title: "Directional Neighborhood Search",
              desc: "For each empty cell, the algorithm traverses 8 directions to select reference points that spatially enclose the interpolation location. This prevents the directional bias that would result from proximity-only selection in track-aligned data.",
              color: "purple",
            },
            {
              step: "4",
              title: "Ordinary Kriging Interpolation",
              desc: "A fitted Gaussian variogram models spatial correlation. The kriging system is solved using an adaptive solver that selects between LU, QR, SVD, or Tikhonov regularization based on the condition number of each matrix, ensuring stability across varying data configurations.",
              color: "amber",
            },
          ].map((s) => (
            <div
              key={s.step}
              className={`flex gap-4 items-start bg-slate-800/50 border rounded-xl p-5 ${
                s.color === "sky"
                  ? "border-sky-400/30"
                  : s.color === "emerald"
                  ? "border-emerald-400/30"
                  : s.color === "purple"
                  ? "border-purple-400/30"
                  : "border-amber-400/30"
              }`}
            >
              <span
                className={`text-lg font-bold shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-sm ${
                  s.color === "sky"
                    ? "bg-sky-400/20 text-sky-400"
                    : s.color === "emerald"
                    ? "bg-emerald-400/20 text-emerald-400"
                    : s.color === "purple"
                    ? "bg-purple-400/20 text-purple-400"
                    : "bg-amber-400/20 text-amber-400"
                }`}
              >
                {s.step}
              </span>
              <div>
                <h3 className="text-white font-semibold mb-1">{s.title}</h3>
                <p className="text-slate-400 text-sm">{s.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* More results */}
      <section className="mb-12">
        <h2 className="text-2xl font-bold mb-6">Additional Results</h2>
        <div className="grid md:grid-cols-2 gap-6">
          <div>
            <img
              src={`${BASE}images/dadip/elevationZoomedIn.jpeg`}
              alt="Zoomed-in elevation map of northern Greenland"
              className="rounded-xl border border-slate-700 w-full"
            />
            <p className="text-slate-400 text-sm mt-2">
              <span className="text-white font-medium">
                Zoomed-in elevation
              </span>{" "}
              &mdash; Northern Greenland detail showing the fine spatial
              resolution preserved by DADIP, including fjord and glacier outlet
              topography.
            </p>
          </div>
          <div>
            <img
              src={`${BASE}images/dadip/roughness5000.jpeg`}
              alt="Surface roughness map of Greenland"
              className="rounded-xl border border-slate-700 w-full"
            />
            <p className="text-slate-400 text-sm mt-2">
              <span className="text-white font-medium">
                Surface roughness map
              </span>{" "}
              &mdash; log(pond_res) roughness values across the ice sheet.
              Coastal regions show high roughness (crevassed terrain) while the
              interior is smooth.
            </p>
          </div>
        </div>

        <div className="mt-6 flex justify-center">
          <div className="max-w-md w-full">
            <img
              src={`${BASE}images/dadip/elevation_standard_deviation.jpeg`}
              alt="Kriging estimation standard deviation"
              className="rounded-xl border border-slate-700 w-full"
            />
            <p className="text-slate-400 text-sm mt-2 text-center">
              <span className="text-white font-medium">
                Kriging estimation uncertainty
              </span>{" "}
              &mdash; Standard deviation map showing higher uncertainty in gaps
              between satellite ground tracks and lower uncertainty along
              well-sampled tracks.
            </p>
          </div>
        </div>
      </section>

      {/* Paper note */}
      <section className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
        <div className="flex items-start gap-3">
          <svg
            className="w-6 h-6 text-sky-400 shrink-0 mt-0.5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"
            />
          </svg>
          <div>
            <h3 className="text-white font-semibold">Research Paper</h3>
            <p className="text-slate-400 text-sm mt-1">
              A research paper on DADIP is currently being authored:{" "}
              <em className="text-slate-300">
                "Advanced Ordinary Kriging Interpolation of Cryospheric
                Roughness and Elevation Maps"
              </em>{" "}
              by Sergio Lopez Gomez de Segura, Ute Herzfeld, and Thomas
              Trantow.
            </p>
          </div>
        </div>
      </section>
    </ProjectDetail>
  );
}
